/*

 BGMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\samra\OneDrive\Bureau\Personal Files\Gameboy developpment\Tile designer\Tiles\Snake\snake.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define backgroundmapWidth 20
#define backgroundmapHeight 18
#define backgroundmapBank 0

extern unsigned char backgroundmap[];

/* End of BGMAP.H */
