/*

 FOOD.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 12 to 13

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char foodToEat[] =
{
  0x3B,0x3B,0x57,0x6D,0xEF,0x8B,0xCE,0x8E,
  0xEA,0x86,0xF2,0x8E,0x44,0x7C,0x38,0x38,
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00
};

/* End of FOOD.C */
