/*

 NUMBERS_LETTERS.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 38

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define numbers_and_lettersBank 0
/* Start of tile array. */
extern unsigned char numbers_and_letters[];

/* End of NUMBERS_LETTERS.H */
